# Generated by Django 5.1.1 on 2024-09-20 13:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500, null=True)),
                (
                    "expire_time",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(1, 9, 20, 16, 40, 10, 643383),
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_own",
                        to="users.user",
                        verbose_name="user_own",
                    ),
                ),
            ],
        ),
    ]
