# Generated by Django 5.1.1 on 2024-09-20 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0003_alter_task_expire_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="task",
            name="expire_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(1, 9, 20, 16, 49, 8, 829659),
                null=True,
            ),
        ),
    ]
