# Generated by Django 5.1.1 on 2024-09-20 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0004_alter_task_created_at_alter_task_expire_time"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="asigned_to",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="asigned_task", to="users.user"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="expire_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(1, 9, 20, 16, 59, 35, 869081),
                null=True,
            ),
        ),
    ]
