# Generated by Django 5.1.1 on 2024-09-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=100)),
                ("family", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
